name: Deva_Tracking
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

  #Developed  by  :Kushal Pandey
  #Github     :https://github.com/pandeykushal

dependencies:
  flutter:
    sdk: flutter

  # State_management
  provider: ^6.1.1
  get: ^4.6.6
  go_router: ^12.1.1

  # NETWORK_CALLS
  flutter_local_notifications: ^16.1.0
  flutter_html: ^3.0.0-beta.2
  dio: ^5.3.4

  # LOCAL STORAGE
  flutter_secure_storage: ^9.0.0

  # FILES
  open_filex: ^4.3.4

  # FIREBASE
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  firebase_auth: ^4.7.2

  # IMAGES
  cached_network_image: ^3.3.0

  # UI
  flutter_screenutil: ^5.9.0
  bot_toast: ^4.1.3
  responsive_framework: ^1.1.1
  cupertino_icons: ^1.0.2
  fpdart: ^1.1.0
  file_picker: ^6.1.1
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.10
  image_picker: ^1.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "asset/icon/logo.png"
  image_path_ios: "asset/icon/logo.png"
  image_path_android: "asset/icon/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - asset/image/
    - asset/icon/

  fonts:
    - family: Inter
      fonts:
        - asset: asset/font/Inter-ExtraLight.ttf #Inter ExtraLight
          weight: 100
          style: normal
        - asset: asset/font/Inter-Light.ttf #Inter Light
          weight: 200
          style: normal
        - asset: asset/font/Inter-Medium.ttf #Inter Light Italic
          weight: 200
          style: italic
        - asset: asset/font/Inter-Regular.ttf #Inter Regular
          weight: 300
          style: normal
        - asset: asset/font/Inter-SemiBold.ttf #Inter SemiBold
          weight: 400
          style: normal
        - asset: asset/font/Inter-Bold.ttf #Inter Bold
          weight: 500
          style: normal
        - asset: asset/font/Inter-ExtraBold.ttf #Inter ExtraBold
          weight: 600
          style: normal
        - asset: asset/font/Inter-Black.ttf #Inter Black
          weight: 700
          style: normal
#Basic template  for the Flutter app Created By :kushal Pandey
# Flutter App by   Kushal Pandey
#Developed  by  :Kushal Pandey
# Linkd in: kushal-pandey-9aa986202/
#website : //kushalpandey.com.np/
##
